const pages = [...document.querySelectorAll('.page')];
const openLetterBtn = document.getElementById('openLetterBtn');
const continueBtn = document.getElementById('continueBtn');
const yesBtn = document.getElementById('yesBtn');
const noBtn = document.getElementById('noBtn');
const answerZone = document.getElementById('answerZone');
const noCounter = document.getElementById('noCounter');
const replayBtn = document.getElementById('replayBtn');
const heartField = document.getElementById('heartField');
const confettiLayer = document.getElementById('confettiLayer');
const musicToggle = document.getElementById('musicToggle');
const bgMusic = document.getElementById('bgMusic');
const letterDate = document.getElementById('letterDate');

let noAttempts = 0;
let musicPlaying = false;
let blockYesUntil = 0;

function showPage(id) {
  pages.forEach(page => page.classList.toggle('active', page.id === id));
}

function formatDate() {
  return new Intl.DateTimeFormat('id-ID', {
    day: 'numeric', month: 'long', year: 'numeric'
  }).format(new Date());
}
letterDate.textContent = formatDate();

openLetterBtn.addEventListener('click', () => {
  openLetterBtn.classList.add('opening');
  tryStartMusic();
  setTimeout(() => showPage('letterPage'), 720);
});

continueBtn.addEventListener('click', () => showPage('questionPage'));

yesBtn.addEventListener('click', (e) => {
  // Prevent the same touchscreen gesture used on NO from activating YES.
  if (Date.now() < blockYesUntil) {
    e.preventDefault();
    e.stopPropagation();
    return;
  }
  showPage('successPage');
  celebrate();
});

function moveNoButton() {
  noAttempts++;
  const zone = answerZone.getBoundingClientRect();
  const btn = noBtn.getBoundingClientRect();

  // Keep it inside the answer area on both mobile and desktop.
  const maxX = Math.max(0, zone.width - btn.width - 10);
  const maxY = Math.max(0, zone.height - btn.height - 10);
  const x = Math.random() * maxX;
  const y = Math.random() * maxY;

  noBtn.style.position = 'absolute';
  noBtn.style.left = `${x}px`;
  noBtn.style.top = `${y}px`;

  const messages = [
    'eh kok kabur 😭',
    'coba lagi wkwk',
    'yang ini susah dipencet ya? 👀',
    'kayaknya tombolnya punya pilihan sendiri 😭',
    'udah deh... sebelah kiri aja 💗'
  ];
  noCounter.textContent = messages[Math.min(noAttempts - 1, messages.length - 1)];

  // Make YES slightly more tempting each time, but cap the size.
  const scale = Math.min(1 + noAttempts * .055, 1.28);
  yesBtn.style.transform = `scale(${scale})`;
}

// Desktop: run away before the pointer can click it.
noBtn.addEventListener('mouseenter', moveNoButton);

// Mobile/tablet: consume the whole gesture on pointerdown.
// A short YES lock prevents click-through after NO changes position.
noBtn.addEventListener('pointerdown', (e) => {
  e.preventDefault();
  e.stopPropagation();
  blockYesUntil = Date.now() + 650;
  moveNoButton();
});

// Cancel any synthetic click generated by a touch browser.
noBtn.addEventListener('click', (e) => {
  e.preventDefault();
  e.stopPropagation();
});

replayBtn.addEventListener('click', () => {
  noAttempts = 0;
  noCounter.textContent = '';
  noBtn.removeAttribute('style');
  yesBtn.removeAttribute('style');
  openLetterBtn.classList.remove('opening');
  confettiLayer.innerHTML = '';
  showPage('openingPage');
});

function spawnHeart() {
  const heart = document.createElement('span');
  heart.className = 'floating-heart';
  heart.textContent = Math.random() > .45 ? '♥' : '♡';
  heart.style.left = `${Math.random() * 100}%`;
  heart.style.fontSize = `${10 + Math.random() * 18}px`;
  heart.style.color = ['#ff91b5','#ef6e9c','#ffc1d5','#d95888'][Math.floor(Math.random()*4)];
  heart.style.animationDuration = `${6 + Math.random() * 6}s`;
  heartField.appendChild(heart);
  setTimeout(() => heart.remove(), 12500);
}
setInterval(spawnHeart, 700);
for (let i = 0; i < 8; i++) setTimeout(spawnHeart, i * 220);

function celebrate() {
  const symbols = ['♥','♡','✦','●','💗'];
  for (let i = 0; i < 70; i++) {
    const piece = document.createElement('span');
    piece.className = 'confetti';
    piece.textContent = symbols[Math.floor(Math.random() * symbols.length)];
    piece.style.left = `${Math.random() * 100}%`;
    piece.style.fontSize = `${10 + Math.random() * 17}px`;
    piece.style.color = ['#ef5d91','#ff9abb','#d74d80','#f9bfd2','#fff'][Math.floor(Math.random()*5)];
    piece.style.animationDuration = `${2.7 + Math.random() * 3}s`;
    piece.style.animationDelay = `${Math.random() * .8}s`;
    confettiLayer.appendChild(piece);
    setTimeout(() => piece.remove(), 7000);
  }
}

async function tryStartMusic() {
  if (!bgMusic.getAttribute('src')) return;
  try {
    await bgMusic.play();
    musicPlaying = true;
    musicToggle.classList.add('playing');
  } catch (_) {
    // Browser may block autoplay or the asset may not exist yet.
  }
}

musicToggle.addEventListener('click', async () => {
  if (musicPlaying) {
    bgMusic.pause();
    musicPlaying = false;
    musicToggle.classList.remove('playing');
  } else {
    await tryStartMusic();
  }
});

// ===============================
// WHATSAPP SETTINGS
// ===============================

document.getElementById("waButton").onclick = function () {
  const phone = "6287723052620";

  const now = new Date();

  const tanggal = now.toLocaleDateString("id-ID", {
    day: "2-digit",
    month: "long",
    year: "numeric"
  });

  const waktu = now.toLocaleTimeString("id-ID", {
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false
  }).replace(/\./g, ":");

  const message = `Haiii 💗

Aku udah baca semuanya...

Dan jawabanku: IYA, AKU MAU! 🥺💕

📅 Tanggal: ${tanggal}
🕐 Waktu: ${waktu} WIB

Suratnya sudah diterima dengan baik yaa 😝💌`;

  const params = new URLSearchParams();
  params.set("phone", phone);
  params.set("text", message);

  window.location.href =
    "https://api.whatsapp.com/send?" + params.toString();
};